"""OpenFOAM blockMeshDict serialization."""

from __future__ import annotations

from pathlib import Path

from .model import MeshModel, TopologyError


def block_mesh_dict(model: MeshModel) -> str:
    """Serialize ``model`` as a deterministic OpenFOAM dictionary."""
    model.validate()
    if not model.blocks:
        raise TopologyError("Cannot export blockMeshDict without at least one block")
    vertex_ids = list(model.vertices)
    bottom_index = {identifier: index for index, identifier in enumerate(vertex_ids)}
    top_offset = len(vertex_ids)

    lines = [
        "/*--------------------------------*- C++ -*----------------------------------*\\",
        "| =========                 |                                                 |",
        "| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |",
        "|  \\    /   O peration     |                                                 |",
        "|   \\  /    A nd           | Generated by BlockDrawer                      |",
        "|    \\/     M anipulation  |                                                 |",
        "\\*---------------------------------------------------------------------------*/",
        "FoamFile",
        "{",
        "    format      ascii;",
        "    class       dictionary;",
        "    object      blockMeshDict;",
        "}",
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //",
        "",
        f"scale {_scalar(model.scale)};",
        "",
        "vertices",
        "(",
    ]
    for identifier in vertex_ids:
        vertex = model.vertices[identifier]
        lines.append(
            f"    ({_scalar(vertex.x)} {_scalar(vertex.y)} {_scalar(model.z_min)})"
            f" // {bottom_index[identifier]}: {identifier} lower"
        )
    for identifier in vertex_ids:
        vertex = model.vertices[identifier]
        lines.append(
            f"    ({_scalar(vertex.x)} {_scalar(vertex.y)} {_scalar(model.z_max)})"
            f" // {bottom_index[identifier] + top_offset}: {identifier} upper"
        )

    lines.extend([")", ";", "", "blocks", "("])
    for block in model.blocks:
        lower = [bottom_index[identifier] for identifier in block.vertices]
        upper = [index + top_offset for index in lower]
        nx, ny, nz = model.block_cell_counts(block)
        indices = " ".join(str(index) for index in lower + upper)
        lines.append(
            f"    hex ({indices}) ({nx} {ny} {nz}) simpleGrading (1 1 1)"
            f" // {block.id}"
        )

    lines.extend([")", ";", "", "edges", "("])
    for current in model.edges():
        geometry = model.edge_geometry.get(current)
        if geometry is None:
            continue
        first_index = bottom_index[current[0]]
        second_index = bottom_index[current[1]]
        if geometry.kind == "arc":
            point_x, point_y = geometry.points[0]
            lines.append(
                f"    arc {first_index} {second_index} "
                f"({_scalar(point_x)} {_scalar(point_y)} {_scalar(model.z_min)})"
            )
            lines.append(
                f"    arc {first_index + top_offset} "
                f"{second_index + top_offset} "
                f"({_scalar(point_x)} {_scalar(point_y)} {_scalar(model.z_max)})"
            )
            continue

        for z, offset in ((model.z_min, 0), (model.z_max, top_offset)):
            lines.append(
                f"    polyLine {first_index + offset} {second_index + offset}"
            )
            lines.append("    (")
            for point_x, point_y in geometry.points:
                lines.append(
                    f"        ({_scalar(point_x)} {_scalar(point_y)} {_scalar(z)})"
                )
            lines.append("    )")

    lines.extend([
        ")",
        ";",
        "",
        "boundary",
        "(",
        ")",
        ";",
        "",
        "mergePatchPairs",
        "(",
        ")",
        ";",
        "",
        "// ************************************************************************* //",
        "",
    ])
    return "\n".join(lines)


def write_block_mesh_dict(model: MeshModel, path: str | Path) -> None:
    Path(path).write_text(block_mesh_dict(model), encoding="utf-8")


def _scalar(value: float) -> str:
    if value == 0.0:
        return "0"
    return format(value, ".15g")
