"""OpenFOAM blockMeshDict serialization."""

from __future__ import annotations

import math
from pathlib import Path

from .domain import TopologyError
from .model import MeshModel


def block_mesh_dict(model: MeshModel) -> str:
    """Serialize ``model`` as a deterministic OpenFOAM dictionary."""
    model.validate()
    if not model.blocks:
        raise TopologyError("Cannot export blockMeshDict without at least one block")
    _validate_cyclic_boundaries(model)
    vertex_ids = list(model.vertices)
    bottom_index = {identifier: index for index, identifier in enumerate(vertex_ids)}
    top_offset = len(vertex_ids)

    lines = [
        "/*--------------------------------*- C++ -*----------------------------------*\\",
        "| =========                 |                                                 |",
        "| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |",
        "|  \\    /   O peration     |                                                 |",
        "|   \\  /    A nd           | Generated by BlockDrawer                      |",
        "|    \\/     M anipulation  |                                                 |",
        "\\*---------------------------------------------------------------------------*/",
        "FoamFile",
        "{",
        "    format      ascii;",
        "    class       dictionary;",
        "    object      blockMeshDict;",
        "}",
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //",
        "",
        f"scale {_scalar(model.scale)};",
        "",
        "vertices",
        "(",
    ]
    for identifier in vertex_ids:
        vertex = model.vertices[identifier]
        lines.append(
            f"    ({_scalar(vertex.x)} {_scalar(vertex.y)} {_scalar(model.z_min)})"
            f" // {bottom_index[identifier]}: {identifier} lower"
        )
    for identifier in vertex_ids:
        vertex = model.vertices[identifier]
        lines.append(
            f"    ({_scalar(vertex.x)} {_scalar(vertex.y)} {_scalar(model.z_max)})"
            f" // {bottom_index[identifier] + top_offset}: {identifier} upper"
        )

    lines.extend([")", ";", "", "blocks", "("])
    for block in model.blocks:
        lower = [bottom_index[identifier] for identifier in block.vertices]
        upper = [index + top_offset for index in lower]
        nx, ny, nz = model.block_cell_counts(block)
        indices = " ".join(str(index) for index in lower + upper)
        grading = " ".join(
            _scalar(value) for value in _block_edge_grading(model, block.vertices)
        )
        lines.append(
            f"    hex ({indices}) ({nx} {ny} {nz}) edgeGrading ({grading})"
            f" // {block.id}"
        )

    lines.extend([")", ";", "", "edges", "("])
    for current in model.edges():
        geometry = model.edge_geometry.get(current)
        if geometry is None:
            continue
        first_index = bottom_index[current[0]]
        second_index = bottom_index[current[1]]
        if geometry.kind == "arc":
            point_x, point_y = geometry.points[0]
            lines.append(
                f"    arc {first_index} {second_index} "
                f"({_scalar(point_x)} {_scalar(point_y)} {_scalar(model.z_min)})"
            )
            lines.append(
                f"    arc {first_index + top_offset} "
                f"{second_index + top_offset} "
                f"({_scalar(point_x)} {_scalar(point_y)} {_scalar(model.z_max)})"
            )
            continue

        for z, offset in ((model.z_min, 0), (model.z_max, top_offset)):
            lines.append(
                f"    {geometry.kind} {first_index + offset} {second_index + offset}"
            )
            lines.append("    (")
            for point_x, point_y in geometry.points:
                lines.append(
                    f"        ({_scalar(point_x)} {_scalar(point_y)} {_scalar(z)})"
                )
            lines.append("    )")

    lines.extend([
        ")",
        ";",
        "",
        "boundary",
        "(",
    ])
    occurrences = model.edge_occurrences()
    for boundary in model.boundaries.values():
        lines.extend([
            f"    {boundary.name}",
            "    {",
            f"        type {boundary.kind};",
        ])
        if boundary.neighbour_patch is not None:
            lines.append(
                f"        neighbourPatch {boundary.neighbour_patch};"
            )
        lines.extend([
            "        faces",
            "        (",
        ])
        for current in model.boundary_edges(boundary.name):
            _, _, directed = occurrences[current][0]
            first, second = directed
            first_index = bottom_index[first]
            second_index = bottom_index[second]
            lines.append(
                f"            ({first_index} {second_index} "
                f"{second_index + top_offset} {first_index + top_offset})"
            )
        lines.extend([
            "        );",
            "    }",
        ])

    z_min_faces: list[tuple[int, int, int, int]] = []
    z_max_faces: list[tuple[int, int, int, int]] = []
    for block in model.blocks:
        lower = [bottom_index[identifier] for identifier in block.vertices]
        upper = [index + top_offset for index in lower]
        # Reverse the lower face so both patch normals point out of the mesh.
        z_min_faces.append((lower[0], lower[3], lower[2], lower[1]))
        z_max_faces.append((upper[0], upper[1], upper[2], upper[3]))
    _append_extrusion_patch(
        lines,
        model.z_min_patch_name,
        model.z_min_patch_type,
        z_min_faces,
        neighbour=(
            model.z_max_patch_name
            if model.z_min_patch_type == "cyclic" else None
        ),
    )
    _append_extrusion_patch(
        lines,
        model.z_max_patch_name,
        model.z_max_patch_type,
        z_max_faces,
        neighbour=(
            model.z_min_patch_name
            if model.z_max_patch_type == "cyclic" else None
        ),
    )

    lines.extend([
        ")",
        ";",
        "",
        "mergePatchPairs",
        "(",
        ")",
        ";",
        "",
        "// ************************************************************************* //",
        "",
    ])
    return "\n".join(lines)


def write_block_mesh_dict(model: MeshModel, path: str | Path) -> None:
    Path(path).write_text(block_mesh_dict(model), encoding="utf-8")


def _scalar(value: float) -> str:
    if value == 0.0:
        return "0"
    return format(value, ".15g")


def _append_extrusion_patch(
    lines: list[str],
    name: str,
    kind: str,
    faces: list[tuple[int, int, int, int]],
    *,
    neighbour: str | None,
) -> None:
    """Append one automatically generated lower/upper extrusion patch."""
    lines.extend([
        f"    {name}",
        "    {",
        f"        type {kind};",
    ])
    if neighbour is not None:
        lines.append(f"        neighbourPatch {neighbour};")
    lines.extend([
        "        faces",
        "        (",
    ])
    for face in faces:
        lines.append(f"            ({' '.join(str(index) for index in face)})")
    lines.extend([
        "        );",
        "    }",
    ])


def _block_edge_grading(
    model: MeshModel,
    vertices: tuple[str, str, str, str],
) -> tuple[float, ...]:
    """Return OpenFOAM's 12 directed edge ratios for an extruded 2D block."""
    first, second, third, fourth = vertices
    x_first = model.edge_expansion_in_direction(first, second)
    x_second = model.edge_expansion_in_direction(fourth, third)
    y_first = model.edge_expansion_in_direction(first, fourth)
    y_second = model.edge_expansion_in_direction(second, third)
    return (
        x_first,
        x_second,
        x_second,
        x_first,
        y_first,
        y_second,
        y_second,
        y_first,
        1.0,
        1.0,
        1.0,
        1.0,
    )


def _validate_cyclic_boundaries(model: MeshModel) -> None:
    """Reject incomplete cyclic pairs before writing an unusable dictionary."""
    checked: set[str] = set()
    for boundary in model.boundaries.values():
        if boundary.kind != "cyclic" or boundary.name in checked:
            continue
        assert boundary.neighbour_patch is not None
        partner = model.boundaries[boundary.neighbour_patch]
        first_edges = model.boundary_edges(boundary.name)
        second_edges = model.boundary_edges(partner.name)
        if not first_edges or not second_edges:
            raise TopologyError(
                f"Cyclic pair {boundary.name!r}/{partner.name!r} needs "
                "at least one assigned edge on each patch"
            )
        first_cells = sorted(model.edge_cells[current] for current in first_edges)
        second_cells = sorted(model.edge_cells[current] for current in second_edges)
        if first_cells != second_cells:
            raise TopologyError(
                f"Cyclic pair {boundary.name!r}/{partner.name!r} needs matching "
                "edge subdivisions"
            )
        first_lengths = sorted(model.edge_length(current) for current in first_edges)
        second_lengths = sorted(model.edge_length(current) for current in second_edges)
        if len(first_lengths) != len(second_lengths) or any(
            not math.isclose(first, second, rel_tol=1.0e-9, abs_tol=1.0e-12)
            for first, second in zip(first_lengths, second_lengths)
        ):
            raise TopologyError(
                f"Cyclic pair {boundary.name!r}/{partner.name!r} needs matching "
                "edge lengths"
            )
        checked.update((boundary.name, partner.name))
